version: "3.9"
services:
  ezpanel:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - "5000"
    networks:
      - web
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - ezpanel
    networks:
      - web
    restart: unless-stopped

networks:
  web: {}
